import gql from "graphql-tag";

export default gql`
  query getBitsDetails($id: String!) {
	bit(slug: $id) {
		id
		title
		snippet
		created_at
		likes_count
		bookmarks_count
		isLiked
		isBookmarked 
		tags
		user {
			id
			name
			email  
		} 
	}
  }
`;
