import gql from "graphql-tag";

export default gql`
  query getBitsOfCurrentUser($id: ID!, $page: Int!) {
    user(id: $id) {
      name
      email
      bits(first: 10, page: $page) {
        paginatorInfo {
          hasMorePages
          total,
          currentPage
        }
        data {
          id
          title
          created_at
          likes_count 
          user {
            name
            email
          }
        }
      }
    }
  }
`;
