import gql from "graphql-tag";

export default gql`
  query getBitsDetails($id: ID!) {
	bit(id: $id) {
		id
		title
		snippet
		created_at
		likes_count
		isLiked
		isBookmarked 
		user {
			id
			name
			email  
		} 
	}
  }
`;
