import gql from "graphql-tag";

export default gql`
  query getBits($page: Int, $search: String) {
    bits(orderBy: [{ field: "created_at", order: DESC }], page: $page, search: $search) {
		paginatorInfo {
			hasMorePages
			total
			currentPage
		},
      data {
        id
        uuid
        slug
        title
        snippet
        tags
        created_at
		likes_count
        user {
          id
          name
          email
        }
      }
    }
  }
`;