import gql from "graphql-tag"; 

export default  gql`
  query getBookmarksOfCurrentUser($page: Int!) {
      bookmarks(first:10, page: $page) {
		  data {
			id
			uuid
			slug
			title
			created_at
			likes_count 
			tags
			user {
				id
				name
				email
			}
		  }
        paginatorInfo {
			lastPage
			perPage
			currentPage
          hasMorePages
          total
        } 
      } 
  }
`;
