import gql from "graphql-tag";

export default gql`
  query categoryWiseBits($name: String!, $page: Int!) {
    category(name: $name) {
      id
      name
      icon
      bits(first: 10, page: $page) {
        paginatorInfo {
          hasMorePages
          total,
          currentPage
        }
        data {
          id
          uuid
          slug
          title
          created_at
          likes_count 
          tags
          user {
            id
            name
            email
          }
        }
      }
    }
  }
`;
